[project]
name = "rl"
version = "0.1.0"
description = "Qwen3 SFT + GRPO"
readme = "README.md"
requires-python = ">=3.11,<3.12"

dependencies = [
    "torch==2.9.0",
    "transformers",
    "datasets",
    "accelerate",
    "peft",
    "trl==0.26.2",
    "bitsandbytes>=0.45.0",
    "unsloth[cu128-torch290]",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.1",
    "math-verify[antlr4-13-2]>=0.9.0",
    "lm-eval>=0.4.11",
    "wandb>=0.25.1",
    "omegaconf>=2.0.6",
    "vllm==0.11.2",
    "unsloth-zoo>=2025.9.12",
    "mlflow>=3.11.1",
]

[[tool.uv.index]]
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
default = true
