base_model_name: /home/chy/.cache/huggingface/hub/models--unsloth--Qwen3-1.7B-Base-unsloth-bnb-4bit/snapshots/c7079ee9a92d69fbe9e6616dea1888bf0fb0bbca
cold_start_model: outputs/sft-qwen3-1.7b
train_dataset: data/grpo/train_grpo_gsm8k_1k_middiff.jsonl
output_dir: outputs/grpo-qwen3-1.7b
seed: 42

max_seq_length: 1024
max_prompt_length: 256
max_completion_length: 384

learning_rate: 1.0e-6
epochs: 1
max_steps: -1
batch_size: 16
gradient_accumulation_steps: 1
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.0
load_in_4bit: true
fast_inference: true
gpu_memory_utilization: 0.5
warmup_ratio: 0.03
weight_decay: 0.0

num_generations: 4
num_iterations: 1
beta: 0.02
loss_type: dr_grpo

reward_correct: 1.0
reward_wrong: 0
reward_parse_fail: -0.5
reward_strict_boxed_bonus: 0
reward_length_coef: 0 #1.0e-4
reward_use_relaxed_correctness: true

temperature: 0.7
top_p: 0.95
top_k:
min_p:
repetition_penalty: 1.0
generation_kwargs:
  remove_invalid_values: true
  renormalize_logits: true
mask_truncated_completions: true
top_entropy_quantile: 1.0

logging_steps: 10
save_strategy: steps
save_steps: 50
save_total_limit: 6
log_completions: true
num_completions_to_print: 2
report_to: wandb
wandb_mode: online
wandb_project: qwen3-math-posttrain
wandb_run_name:
wandb_tags: []
