model_name: /home/chy/.cache/huggingface/hub/models--Qwen--Qwen3-1.7B-Base/snapshots/ea980cb0a6c2ae4b936e82123acc929f1cec04c1
#/home/chy/.cache/huggingface/hub/models--Qwen--Qwen3-1.7B-Base/snapshots/ea980cb0a6c2ae4b936e82123acc929f1cec04c1
#/home/chy/.cache/huggingface/hub/models--unsloth--Qwen3-1.7B-Base-unsloth-bnb-4bit/snapshots/c7079ee9a92d69fbe9e6616dea1888bf0fb0bbca
seed: 42
train_dataset: data/train_sft.jsonl
eval_dataset: data/eval/gsm8k_dev200.jsonl
test_dataset: data/eval/math500_test.jsonl
output_dir: outputs/sft-qwen3-1.7b

# lora
max_seq_length: 1024
learning_rate: 1.0e-4
epochs: 2
batch_size: 4
gradient_accumulation_steps: 4
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.0
warmup_ratio: 0.03
weight_decay: 0.01

# eval
eval_max_new_tokens: 512
eval_backend: vllm
eval_attn_implementation: sdpa
eval_gpu_memory_utilization: 0.8
