_wandb:
    value:
        cli_version: 0.25.1
        e:
            butca53w6u65obz83bod7fdbgun8hbv3:
                args:
                    - --config
                    - configs/grpo/train_cheap.yaml
                codePath: scripts/train_grpo.py
                codePathLocal: scripts/train_grpo.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "1081101176832"
                        used: "109267849216"
                email: barry.haoyuc@gmail.com
                executable: /home/chy/code/active/post_train/.venv/bin/python
                git:
                    commit: b8c0d1a84e1afc1b026ecfd4483472b4eef25e25
                gpu: NVIDIA GeForce RTX 5070 Ti Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      memoryTotal: "12820938752"
                      name: NVIDIA GeForce RTX 5070 Ti Laptop GPU
                      uuid: GPU-a6efad2a-bcf0-4329-375e-7265db9017d6
                host: DESKTOP-DH0MILO
                memory:
                    total: "16771153920"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/chy/code/active/post_train/scripts/train_grpo.py
                python: CPython 3.11.14
                root: /home/chy/code/active/post_train
                startedAt: "2026-04-02T20:38:17.573208Z"
                writerId: butca53w6u65obz83bod7fdbgun8hbv3
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 84
                - 95
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 84
                - 95
                - 98
            "3":
                - 13
                - 16
            "4": 3.11.14
            "5": 0.25.1
            "6": 4.56.2
            "12": 0.25.1
            "13": linux-x86_64
batch_size:
    value: 1
gradient_accumulation_steps:
    value: 8
learning_rate:
    value: 1e-06
loss_type:
    value: dr_grpo
max_completion_length:
    value: 256
max_prompt_length:
    value: 768
num_generations:
    value: 4
output_dir:
    value: outputs/grpo_cheap
train_dataset:
    value: data/grpo/train.jsonl
use_vllm:
    value: false
vllm_mode:
    value: colocate
